---

- name: apply common configuration
  hosts:
    - arenadata-adcm
  become: true
  become_user: root
  roles:
    - common
    - trombik.hosts
    - geerlingguy.docker
    - geerlingguy.fluentd
  post_tasks:
    - name: syslog write to fluentd socket, change config
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        line: "*.* @127.0.0.1:5140"
    - name: syslog write to fluentd socket, restart service
      ansible.builtin.service:
        name: rsyslog
        state: restarted

- name: apply basic adcm configuration
  hosts:
    - arenadata-adcm
  become: true
  become_user: root
  roles:
    - iac-ansible-arenadata
  vars:
    basic_configuration: true
