- name: Simple Example
  hosts: elastic
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 7.15.1
    es_heap_size: 1g
    es_config:
      network.host: "0.0.0.0"
      discovery.type: single-node
    es_plugins:
     - plugin: ingest-attachment
