---

- name: apply common configuration
  hosts:
    - app-analytics
  become: true
  vars:
    java_packages:
      - openjdk-11-jdk
  become_user: root
  roles:
    - common
    - trombik.hosts
    - geerlingguy.java
    - iac-ansible-jupyterhub
  post_tasks:
    - name: syslog write to fluentd socket, change config
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        line: "*.* @127.0.0.1:5140"
    - name: syslog write to fluentd socket, restart service
      ansible.builtin.service:
        name: rsyslog
        state: restarted
