---

- name: apply common configuration
  hosts:
    - vault-nodes
  become: true
  become_user: root
  roles:
    - common
    - trombik.hosts
    - geerlingguy.fluentd
  post_tasks:
    - name: syslog write to fluentd socket, change config
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        line: "*.* @127.0.0.1:5140"
    - name: syslog write to fluentd socket, restart service
      ansible.builtin.service:
        name: rsyslog
        state: restarted

- name: apply vault configuration
  hosts:
    - nifi-nodes
  become: true
  become_user: root
  roles:
    - ansible-role-vault
